Add box_namespace to track nested Box names
cdgriffith/Box pull request #240
Opened 2023-01-23 02:54 UTC by JacobHayes

I'd like to track the "namespace" of nested boxes, which is hard to do in a subclass because of the (necessary) recursive conversions during `__init__` and other actions. To handle this, I added a new `box_namespace` parameter, which is tracked in `_box_config`, to allow propagating and extending the namespace as we create nested boxes.

Closes #226

---

This recreates https://github.com/cdgriffith/Box/pull/227 after the `develop` branch was replaced. I updated it to avoid creating an intermediate box config when not needed (as per https://github.com/cdgriffith/Box/pull/227#discussion_r946289689). There were two [open questions](https://github.com/cdgriffith/Box/pull/227#issuecomment-1216089919) on how to label elements of lists and whether to add a `box_history` accessor, but I'd be fine 1: punting for now and 2: just accessing the config.

2023-01-25 00:14 UTC, cdgriffith commented on test/test_box.py
> +
```
        box[None] = {"32": 33}
        assert box[None]._box_config["box_namespace"] == (None, )
```

Currently fails

2023-01-25 00:15 UTC, cdgriffith commented on box/box.py
> +        if extra_namespace is not None:
Need to change this to use a unique pre-set object like we do with `NO_DEFAULT` otherwise anything with `None` as a key will lose its namespace

2023-01-25 00:17 UTC, cdgriffith requested changes
This is a great addition, thank you! 

I will want to test this some more, and does need the change to support `None` keys, but other than that I am excited for this add!

2023-01-25 16:53 UTC, JacobHayes commented on box/box.py
> +from typing import Any, Dict, Generator, List, Tuple, Union, Type, Optional
Oops, I forgot I had `isort` disabled here and got lazy with the merge conflict. Fixed!

2023-01-25 16:54 UTC, JacobHayes commented
Pushed a fix for `None` keys and the dup imports!

2023-01-28 00:15 UTC, cdgriffith approved these changes
Thanks for the updates!

2023-01-28 01:26 UTC, merged